[package]
name = "system_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
