
import { VerticalBox, GroupBox, TabWidget, StandardTableView, ScrollView } from "std-widgets.slint";

export struct InterfaceInfo {
    name: string,
    ip: string,
}

export struct RxInfo {
    name: string,
    rx_bytes: string,
    rx_packets: string,
    rx_errors: string,
    rx_drops: string,
    rx_fifo: string,
    rx_frame: string,
    rx_compressed: string,
    rx_multicast: string,
}

export struct TxInfo {
    name: string,
    tx_bytes: string,
    tx_packets: string,
    tx_errors: string,
    tx_drops: string,
    tx_fifo: string,
    tx_colls: string,
    tx_compressed: string,
    tx_carrier: string,
}

export component NetworkView {
    in property <[InterfaceInfo]> interface-list;
    in property <[RxInfo]> rx_list;
    in property <[TxInfo]> tx_list;
    // Définir les titres des colonnes
        property <[string]> headers: [
        "Interface",
        "Bytes",
        "Packets",
        "Errors",
        "Drops",
        "FIFO",
        "Collisions",
        "Compressed",
        "Carrier"
    ];

    width: 100%;

    VerticalBox {
        GroupBox {
            title: "Network";
            VerticalBox {
                // Interface Information
                GroupBox {
                    title: "Interface Information";

                    ScrollView {
                        VerticalBox {
                            for interface in interface-list: HorizontalLayout {
                                Text {
                                    text: "Interface: ";
                                    width: 150px;
                                }

                                Text {
                                    text: interface.name;
                                    width: 150px;
                                }

                                Text {
                                    text: "IP Address: ";
                                    width: 150px;
                                }

                                Text {
                                    text: interface.ip;
                                    width: 150px;
                                }
                            }
                        }
                    }
                }

                // Network Statistics
                TabWidget {
                    Tab {
                        title: "RX";
                        ScrollView { // Pour pouvoir faire défiler si la liste est longue
                                        HorizontalLayout {
                                padding: 10px;
                                padding-left: 0px;
                                spacing: 0px;
                                for header_text in headers: Text {
                                    text: header-text;
                                    horizontal-alignment: center;
                                    width: 150px;
                                }
                            }

                            VerticalLayout { // Organise les éléments verticalement
                                padding-top: 75px;
                                spacing: -10px;  // Espace entre les lignes de texte
                                            for interface_data in root.rx_list: Text {
                                    GridLayout {
                                        Row {
                                            Text {
                                                text: interface_data.name;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_bytes;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_packets;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_errors;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_drops;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_fifo;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_frame;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_compressed;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.rx_multicast;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Tab {
                        title: "TX";

                        ScrollView { // Pour pouvoir faire défiler si la liste est longue
                                        HorizontalLayout {
                                padding: 10px; // Un peu d'espace autour
                                padding-left: 0px;
                                spacing: 0px;
                                for header_text in headers: Text {
                                    text: header-text;
                                    horizontal-alignment: center;
                                    width: 150px;
                                }
                            }

                            VerticalLayout { // Organise les éléments verticalement
                                padding-top: 75px;
                                spacing: -10px;  // Espace entre les lignes de texte
                                            for interface_data in root.tx_list: Text {
                                    GridLayout {
                                        Row {
                                            Text {
                                                text: interface_data.name;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_bytes;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_packets;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_errors;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_drops;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_fifo;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_colls;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_compressed;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }

                                            Text {
                                                text: interface_data.tx_carrier;
                                                horizontal-alignment: center;
                                                width: 150px;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
